apiVersion: v2
name: otel-collector-chart
version: 0.1.0

dependencies:
  - name: opentelemetry-collector
    version: 0.105.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
