mode: deployment

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true

image:
  repository: "otel/opentelemetry-collector-contrib"

config:
  exporters:
    otlp:
      endpoint: "http://tempo.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true
    otlphttp:
      endpoint: "http://loki-gateway.monitoring.svc.cluster.local/otlp"
    prometheus:
      endpoint: "0.0.0.0:9090"
  receivers:
    jaeger: null
    prometheus:
      config:
        scrape_configs:
          - job_name: 'backend-rust'
            scrape_interval: 30s
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [ __meta_kubernetes_pod_label_app ]
                action: keep
                regex: backend-rust
              - source_labels: [ __address__ ]
                target_label: __address__
                replacement: $1:8080
    zipkin: null
  service:
    pipelines:
      traces:
        receivers:
          - otlp
        exporters:
          - otlp
      metrics:
        receivers:
          - otlp
          - prometheus
        exporters:
          - prometheus
      logs:
        exporters:
          - otlphttp

serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: metrics

ports:
  metrics:
    enabled: true
    containerPort: 9090
    servicePort: 9090
    protocol: TCP

resources:
  requests:
    memory: '256Mi'
    cpu: '20m'
  limits:
    memory: '256Mi'
    cpu: '100m'