version: "3.9"
services:
  app:
    image: ghcr.io/and-mora/expenses-monitor:${tag}
    ports:
      - "443:443"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        failure_action: rollback
        order: start-first
    volumes:
      - /etc/letsencrypt/live/expmonitor.freeddns.org/privkey.pem:/etc/ssl/private/key.pem
      - /etc/letsencrypt/live/expmonitor.freeddns.org/fullchain.pem:/etc/ssl/certs/cert.pem
    networks:
      - expenses_monitor

networks:
  expenses_monitor:
    external: true
