version: "3.9"
services:
  postgres:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_CONNECTION_URI: "postgres://host.docker.internal"
