import type {
  BankingConnectionSummary,
  StagingTransaction,
} from '@/types/api';

export const mockBankConnections: BankingConnectionSummary[] = [
  {
    connectionId: 'conn-1',
    provider: 'mock',
    connectionLabel: 'Primary Checking',
    accountId: 'acc-001',
    accountLabel: 'Checking Account',
    status: 'connected',
    lastSyncAt: '2026-03-20T09:15:00Z',
    lastSyncStatus: 'success',
    lastSyncMessage: 'Synced successfully',
    createdCount: 3,
    updatedCount: 1,
    duplicateCount: 0,
    syncedAt: '2026-03-20T09:15:00Z',
    accounts: [
      {
        accountId: 'acc-001',
        accountLabel: 'Checking Account',
        iban: 'DE00 0000 0000 0000 0000 00',
        currency: 'EUR',
        balanceInCents: 256_000,
      },
    ],
  },
  {
    connectionId: 'conn-2',
    provider: 'mock',
    connectionLabel: 'Shared Savings',
    accountId: 'acc-002',
    accountLabel: 'Savings Account',
    status: 'syncing',
    lastSyncAt: '2026-03-26T13:30:00Z',
    lastSyncStatus: 'running',
    lastSyncMessage: 'Synchronizing transaction history',
    createdCount: 0,
    updatedCount: 0,
    duplicateCount: 0,
    syncedAt: '2026-03-26T13:30:00Z',
    accounts: [
      {
        accountId: 'acc-002',
        accountLabel: 'Savings Account',
        iban: 'DE11 1111 1111 1111 1111 11',
        currency: 'EUR',
        balanceInCents: 892_500,
      },
    ],
  },
];

export const mockStagingTransactions: StagingTransaction[] = [
  {
    id: 'stg-1',
    connectionId: 'conn-1',
    provider: 'mock',
    bankTransactionId: 'bank-tx-1001',
    amountInCents: -1299,
    currency: 'EUR',
    bookingDate: '2026-03-25',
    valueDate: '2026-03-25',
    creditorName: 'Streaming Service',
    debtorName: 'Test User',
    remittanceInfo: 'Monthly subscription',
    suggestedCategory: 'entertainment',
    suggestedMerchant: 'Streaming Service',
    status: 'pending',
    createdAt: '2026-03-25T10:00:00Z',
    updatedAt: '2026-03-25T10:00:00Z',
  },
  {
    id: 'stg-2',
    connectionId: 'conn-1',
    provider: 'mock',
    bankTransactionId: 'bank-tx-1002',
    amountInCents: -8450,
    currency: 'EUR',
    bookingDate: '2026-03-24',
    valueDate: '2026-03-24',
    creditorName: 'Supermarket',
    debtorName: 'Test User',
    remittanceInfo: 'Weekly groceries',
    suggestedCategory: 'food',
    suggestedMerchant: 'Supermarket',
    status: 'reviewed',
    createdAt: '2026-03-24T09:00:00Z',
    updatedAt: '2026-03-24T12:00:00Z',
  },
  {
    id: 'stg-3',
    connectionId: 'conn-2',
    provider: 'mock',
    bankTransactionId: 'bank-tx-2001',
    amountInCents: 250000,
    currency: 'EUR',
    bookingDate: '2026-03-21',
    valueDate: '2026-03-21',
    creditorName: 'Acme Corp',
    debtorName: 'Test User',
    remittanceInfo: 'Salary',
    suggestedCategory: 'income',
    suggestedMerchant: 'Acme Corp',
    status: 'pending',
    createdAt: '2026-03-21T08:00:00Z',
    updatedAt: '2026-03-21T08:00:00Z',
  },
  {
    id: 'stg-4',
    connectionId: 'conn-2',
    provider: 'mock',
    bankTransactionId: 'bank-tx-2002',
    amountInCents: -5600,
    currency: 'EUR',
    bookingDate: '2026-03-18',
    valueDate: '2026-03-18',
    creditorName: 'Fuel Station',
    debtorName: 'Test User',
    remittanceInfo: 'Fuel card',
    suggestedCategory: 'transport',
    suggestedMerchant: 'Fuel Station',
    status: 'imported',
    importedPaymentId: 'payment-9001',
    createdAt: '2026-03-18T14:00:00Z',
    updatedAt: '2026-03-18T15:00:00Z',
  },
];
