version: "3.9"
services:
  app:
    image: ghcr.io/and-mora/expenses-monitor:${tag}
    ports:
      - "8443:8443"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        failure_action: rollback
    depends_on:
      - postgres
    environment:
      DB_CONNECTION_URI: "r2dbc:postgresql://postgres/postgres"
      DB_SCHEMA: expenses
      FRONTEND_ORIGIN_URL: "https://localhost:5173"
      DB_BACKEND_USER: backend_user
    volumes:
      - /etc/letsencrypt/live/expmonitor.freeddns.org/privkey.pem:/key.pem
      - /etc/letsencrypt/live/expmonitor.freeddns.org/fullchain.pem:/cert.pem
    networks:
      - expenses_monitor
    secrets:
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD
      - DB_BACKEND_PASSWORD

networks:
  expenses_monitor:
    external: true

secrets:
  BASIC_AUTH_USERNAME:
    external: true
  BASIC_AUTH_PASSWORD:
    external: true
  DB_BACKEND_PASSWORD:
    external: true
