---
# Gateway for ArgoCD namespace
# cert-manager gateway-shim auto-creates Certificate resources from the annotation
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: argocd
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: traefik
  listeners:
    - name: https
      hostname: argocd.expmonitor.freeddns.org
      port: 8443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-server-tls
      allowedRoutes:
        namespaces:
          from: Same

    - name: http
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
