REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE expenses-monitor FROM PUBLIC;

-- Read only
CREATE ROLE read_only;
GRANT CONNECT ON DATABASE expenses-monitor TO read_only;
GRANT USAGE ON SCHEMA expenses TO read_only;
GRANT SELECT ON ALL TABLES IN SCHEMA expenses TO read_only;
--ALTER DEFAULT PRIVILEGES IN SCHEMA expenses GRANT SELECT ON TABLES TO read_only;

-- Read-write
CREATE ROLE read_write;

GRANT CONNECT ON DATABASE expenses-monitor TO read_write;
GRANT USAGE, CREATE ON SCHEMA expenses TO read_write;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA expenses TO read_write;
--ALTER DEFAULT PRIVILEGES IN SCHEMA expenses GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO read_write;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA expenses TO read_write;
--ALTER DEFAULT PRIVILEGES IN SCHEMA expenses GRANT USAGE ON SEQUENCES TO read_write;

-- users
CREATE USER grafana_user WITH PASSWORD 'abc12345';
GRANT read_only TO grafana_user;

CREATE USER backend_user WITH PASSWORD 'abc12345';
GRANT read_write TO backend_user;
