apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    postgres-password: AgAA7zPNUR0tybc/wOfFHa4dxFTsYcEh5sqIgAsGUTBOO4hcvIhF6ZJWbiC2VUlb8R6KKUEvmz5FGlsKCUv2WErRKLMCHnJ7no2ButJAT5JoTB6TE0n2Q8Y5n0ZVZkSiv0tKfaW3SUWmEVqs0J+eKIVYNW3bJx+00K1C0X+SswoE23Knojco7gABjzhF0VYdPfajb9>
  template:
    metadata:
      name: postgresql
      namespace: default
    type: Opaque

---
#
#apiVersion: bitnami.com/v1alpha1
#kind: SealedSecret
#metadata:
#  name: users-secret
#spec:
#  encryptedData:
#    KEYCLOAK_DB:
#    KEYCLOAK_PASSWORD:
#    KEYCLOAK_USER:
