ARG PROMETHEUS_VERSION=v2.49.1@sha256:beb5e30ffba08d9ae8a7961b9a2145fc8af6296ff2a4f463df7cd722fcbfc789

FROM prom/prometheus:$PROMETHEUS_VERSION

COPY config/prometheus.yml /etc/prometheus/prometheus.yml
