apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: c8fbcbf5-8f4f-4640-8d37-887b135a905e
    url: postgres:5432
    database: $DATABASE
    user: $DB_GRAFANA_USERNAME
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    secureJsonData:
      password: $DB_GRAFANA_PASSWORD
    readOnly: true