apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-rust
  name: backend-rust
  namespace: expenses-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-rust
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-rust
    spec:
      containers:
        - image: ghcr.io/and-mora/expenses-monitor:v0.7.3-backend-rust
          name: backend-rust
          env:
            - name: APP_DATABASE__HOST
              valueFrom:
                secretKeyRef:
                  name: db-connection-string
                  key: host
            - name: APP_DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-db-credentials
                  key: postgres-password
            - name: APP_DATABASE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-db-credentials
                  key: postgres-username
            - name: APP_OTLP__GRPC_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
#            - name: BASIC_AUTH_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: backend-user-credentials
#                  key: user-password
#            - name: BASIC_AUTH_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: backend-user-credentials
#                  key: user-username
#            - name: FRONTEND_ORIGIN_URL
#              value: "https://expmonitor.freeddns.org"
#            - name: OTEL_EXPORTER_OTLP_ENDPOINT
#              valueFrom:
#                configMapKeyRef:
#                  name: backend-config
#                  key: OTEL_EXPORTER_OTLP_ENDPOINT
#            - name: OTEL_SERVICE_NAME
#              valueFrom:
#                configMapKeyRef:
#                  name: backend-config
#                  key: OTEL_SERVICE_NAME
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            failureThreshold: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            failureThreshold: 15
            periodSeconds: 10
      automountServiceAccountToken: false

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-rust
  name: backend-rust
  namespace: expenses-monitor
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend-rust
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  generation: 1
  name: backend-rust
  namespace: expenses-monitor
spec:
  ingressClassName: public
  rules:
    - host: api-rust.expmonitor.freeddns.org
      http:
        paths:
          - backend:
              service:
                name: backend-rust
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - api-rust.expmonitor.freeddns.org
      secretName: backend-rust-tls
