{
 "title": "Andamento generale",
 "time": { "from": "now-9M", "to": "now" },
 "panels": [
  { "title": "Andamenti totali", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Andamento entrate totali",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select * FROM (select DATE_TRUNC('month',accounting_date) AS time, sum(amount) as entrate, category\nFROM payments \nWHERE accounting_date BETWEEN $__timeFrom() AND $__timeTo() and amount > 0\nGROUP BY DATE_TRUNC('month', accounting_date), category\nUNION\nselect DATE_TRUNC('month',accounting_date) AS time, sum(amount) as entrate, 'totale'\nFROM payments \nWHERE accounting_date BETWEEN $__timeFrom() AND $__timeTo() and amount > 0\nGROUP BY DATE_TRUNC('month', accounting_date)) unione\norder by time\n\n"
    }
   ]
  },
  {
   "title": "Andamento uscite totali",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, sum(abs(amount)) as uscite\nFROM payments \nWHERE $__timeFilter(accounting_date) and amount < 0\nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time\n\n"
    }
   ]
  },
  {
   "title": "Andamento uscite fisse",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select * FROM (select DATE_TRUNC('month',accounting_date) AS time, sum(amount * -1) as uscite_fisse, category\nFROM payments \nWHERE $__timeFilter(accounting_date) and category in ('affitto', 'bolletta', 'condominio')\nGROUP BY DATE_TRUNC('month', accounting_date), category\nUNION\nselect DATE_TRUNC('month',accounting_date) AS time, sum(amount * -1) as entrate, 'totale'\nFROM payments \nWHERE $__timeFilter(accounting_date) and category in ('affitto', 'bolletta', 'condominio')\nGROUP BY DATE_TRUNC('month', accounting_date)) unione\norder by time\n\n"
    }
   ]
  },
  {
   "title": "Andamento spese mensili per categoria",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, category, sum(abs(amount)) as spesa\nfrom expenses.payments\nwhere accounting_date BETWEEN $__timeFrom() AND $__timeTo() and amount < 0\nGROUP BY DATE_TRUNC('month', accounting_date), category\norder by time"
    }
   ]
  },
  {
   "title": "Raggruppamento spese per categoria",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select accounting_date as time, category, amount * -1 as spesa\nfrom expenses.payments\nwhere accounting_date BETWEEN $__timeFrom() AND $__timeTo() and amount < 0\norder by time"
    }
   ]
  },
  {
   "title": "Uscite mensili",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, percentile_disc(0.5) within group (order by abs(payments.amount)) as \"p(50)\", avg(abs(amount))\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) and amount < 0\nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time"
    }
   ]
  },
  { "title": "aggregati", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Bilancio mensile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, sum(amount) as bilancio\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) \nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time"
    }
   ]
  },
  {
   "title": "spese_fisse/stipendio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month', p1.accounting_date) as time, \n  abs(sum(p1.amount))::float * 100 / abs(avg(p2.amount))::float as affitto_stipendio_rate\nFROM payments p1\njoin payments p2 on DATE_TRUNC('month', p1.accounting_date) = DATE_TRUNC('month', p2.accounting_date)\nwhere p1.category in ('affitto', 'bolletta', 'condominio') and p2.category = 'stipendio' and p1.accounting_date BETWEEN $__timeFrom() and $__timeTo() \ngroup by DATE_TRUNC('month', p1.accounting_date)\norder by time"
    }
   ]
  },
  {
   "title": "affitto/stipendio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 14, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month', p1.accounting_date) as time, \n  abs(sum(p1.amount))::float * 100 / abs(sum(p2.amount))::float as affitto_stipendio_rate\nFROM payments p1\njoin payments p2 on DATE_TRUNC('month', p1.accounting_date) = DATE_TRUNC('month', p2.accounting_date)\nwhere p1.category = 'affitto' and p2.category = 'stipendio' and p1.accounting_date BETWEEN $__timeFrom() and $__timeTo() \ngroup by DATE_TRUNC('month', p1.accounting_date), p1.category\norder by time"
    }
   ]
  }
 ]
}