{
 "title": "Monitoraggio mese corrente",
 "time": { "from": "now/M", "to": "now/M" },
 "panels": [
  { "title": "Contatori", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "spese_fisse/stipendio",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month', p1.accounting_date) as time, \n  abs(sum(p1.amount/100))::float * 100 / abs(avg(p2.amount/100))::float as affitto_stipendio_rate\nFROM payments p1\njoin payments p2 on DATE_TRUNC('month', p1.accounting_date) = DATE_TRUNC('month', p2.accounting_date)\nwhere p1.category in ('affitto', 'bolletta', 'condominio') and p2.category = 'stipendio' and p1.accounting_date BETWEEN $__timeFrom() and $__timeTo() \ngroup by DATE_TRUNC('month', p1.accounting_date)\norder by time"
    }
   ]
  },
  {
   "title": "affitto/stipendio",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month', p1.accounting_date) as time, \n  abs(sum(p1.amount/100))::float * 100 / abs(sum(p2.amount/100))::float as affitto_stipendio_rate\nFROM payments p1\njoin payments p2 on DATE_TRUNC('month', p1.accounting_date) = DATE_TRUNC('month', p2.accounting_date)\nwhere p1.category = 'affitto' and p2.category = 'stipendio' and p1.accounting_date BETWEEN $__timeFrom() and $__timeTo() \ngroup by DATE_TRUNC('month', p1.accounting_date), p1.category\norder by time"
    }
   ]
  },
  {
   "title": "Bilancio mensile",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, sum(amount/100) as bilancio\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) \nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time"
    }
   ]
  },
  { "title": "Andamenti", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "spese_fisse/stipendio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month', p1.accounting_date) as time, \n  abs(sum(p1.amount/100))::float * 100 / abs(avg(p2.amount/100))::float as affitto_stipendio_rate\nFROM payments p1\njoin payments p2 on DATE_TRUNC('month', p1.accounting_date) = DATE_TRUNC('month', p2.accounting_date)\nwhere p1.category in ('affitto', 'bolletta', 'condominio') and p2.category = 'stipendio' and p1.accounting_date BETWEEN $__timeFrom() and $__timeTo() \ngroup by DATE_TRUNC('month', p1.accounting_date)\norder by time"
    }
   ]
  },
  {
   "title": "affitto/stipendio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month', p1.accounting_date) as time, \n  abs(sum(p1.amount/100))::float * 100 / abs(sum(p2.amount/100))::float as affitto_stipendio_rate\nFROM payments p1\njoin payments p2 on DATE_TRUNC('month', p1.accounting_date) = DATE_TRUNC('month', p2.accounting_date)\nwhere p1.category = 'affitto' and p2.category = 'stipendio' and p1.accounting_date BETWEEN $__timeFrom() and $__timeTo() \ngroup by DATE_TRUNC('month', p1.accounting_date), p1.category\norder by time"
    }
   ]
  },
  {
   "title": "Uscite per categoria mese corrente",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select\n  DATE_TRUNC('month', accounting_date) as time,\n  category,\n  abs(sum(amount/100)) as totale\nFrom\n  payments\nwhere\n  amount < 0\n  and accounting_date BETWEEN $__timeFrom()\n  and $__timeTo()\nGROUP BY\n  DATE_TRUNC('month', accounting_date),\n  category\norder by\n  totale desc"
    },
    { "expression": "A", "type": "threshold" }
   ]
  },
  {
   "title": "Bilancio mensile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, sum(amount/100) as bilancio\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) \nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time"
    }
   ]
  }
 ]
}