{
 "title": "Ticket & welfare",
 "time": { "from": "2022-09-30T22:00:00.000Z", "to": "now" },
 "panels": [
  { "title": "ticket restaurant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "bilancio complessivo",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select category, sum(amount)/100 from payments\nWHERE category = 'ticket'\ngroup by category"
    }
   ]
  },
  {
   "title": "bilancio mensile ticket",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, sum(amount)/100 as bilancio\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) and category = 'ticket'\nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time"
    }
   ]
  },
  {
   "title": "spese ticket per merchant",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select merchant_name, sum(amount)/-100 as co\nfrom payments \nwhere $__timeFilter(accounting_date) and category = 'ticket' and amount < 0\ngroup by merchant_name"
    }
   ]
  },
  {
   "title": "split entrate/uscite ticket",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) as time, 'entrate', sum(amount)/100 as welfare\nfrom payments \nwhere category = 'ticket' and $__timeFilter(accounting_date) and amount > 0\ngroup by category, DATE_TRUNC('month',accounting_date)\nUNION\nselect DATE_TRUNC('month',accounting_date) as time, 'uscite', sum(amount)/100 as entrate\nfrom payments \nwhere category = 'ticket' and $__timeFilter(accounting_date) and amount < 0\ngroup by category, DATE_TRUNC('month',accounting_date)\norder by time"
    }
   ]
  },
  { "title": "welfare", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "entrata complessiva",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select category, sum(amount)/100 from payments\nWHERE category = 'welfare' and amount > 0\ngroup by category"
    }
   ]
  },
  {
   "title": "saldo Tezenis",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select category, sum(amount)/100 from payments\nWHERE category = 'welfare' and merchant_name = 'Tezenis'\ngroup by category"
    }
   ]
  },
  {
   "title": "saldo H&M",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select category, sum(amount)/100 from payments\nWHERE category = 'welfare' and merchant_name = 'H&M'\ngroup by category"
    }
   ]
  },
  {
   "title": "saldo buoni edenred",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select category, sum(amount)/100 from payments\nWHERE category = 'welfare' and merchant_name not in('Tezenis', 'H&M')\ngroup by category"
    }
   ]
  },
  {
   "title": "saldo totale",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select sum(amount)/100 as bilancio\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) and category = 'welfare'"
    }
   ]
  },
  {
   "title": "spese welfare per merchant",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select merchant_name, sum(amount)/-100 as co\nfrom payments \nwhere $__timeFilter(accounting_date) and category = 'welfare' and amount < 0\ngroup by merchant_name\n"
    }
   ]
  }
 ]
}