version: "3.9"
services:
  grafana:
    image: ghcr.io/and-mora/expenses-monitor:${tag}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        failure_action: rollback
        order: start-first
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://localhost:3000/api/health", "--no-check-certificate" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      DATABASE: postgres
      DB_GRAFANA_USERNAME: grafana_user
    entrypoint: [ '/bin/sh', '-c', 'export DB_GRAFANA_PASSWORD=$$(cat /run/secrets/DB_GRAFANA_PASSWORD); /run.sh' ]
    ports:
      - '3000:3000'
    volumes:
      - /etc/letsencrypt/live/expmonitor.freeddns.org/privkey.pem:/etc/grafana/grafana.key
      - /etc/letsencrypt/live/expmonitor.freeddns.org/fullchain.pem:/etc/grafana/grafana.crt
      - storage:/var/lib/grafana
    networks:
      - expenses_monitor
    secrets:
      - DB_GRAFANA_PASSWORD

secrets:
  DB_GRAFANA_PASSWORD:
    external: true

volumes:
  storage: { }

networks:
  expenses_monitor:
    external: true
