version: "3.9"
services:
  grafana_expenses:
    image: ghcr.io/and-mora/expenses-monitor:${VERSION}
    container_name: grafana_expenses
    environment:
      DATABASE: postgres
      DB_GRAFANA_USERNAME: grafana_user
      DB_GRAFANA_PASSWORD_FILE: /run/secrets/DB_GRAFANA_PASSWORD
    ports:
     - '3000:3000'
    volumes:
     - /etc/letsencrypt/live/expmonitor.freeddns.org/privkey.pem:/etc/grafana/grafana.key
     - /etc/letsencrypt/live/expmonitor.freeddns.org/fullchain.pem:/etc/grafana/grafana.crt
     - storage:/var/lib/grafana
    networks:
      - expenses_monitor
    secrets:
      - DB_GRAFANA_PASSWORD

secrets:
  DB_GRAFANA_PASSWORD:
    external: true

volumes:
  storage: {}

networks:
  expenses_monitor:
    external: true
