version: "3.8"
services:
  grafana_expenses:
    image: grafana/grafana-oss:9.5.3
    container_name: grafana_expenses
    restart: unless-stopped
    #environment:
    # - GF_SERVER_ROOT_URL=http://my.grafana.server/
    # - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
     - ./provisioning:/etc/grafana/provisioning
     - ./dashboards:/var/lib/grafana/dashboards
    networks:
      - expenses-monitor_default

networks:
  expenses-monitor_default:
    name: expenses-monitor_default
    external: true