version: "3.9"
services:
  grafana_expenses:
    image: ghcr.io/and-mora/expenses-monitor:${VERSION}
    container_name: grafana_expenses
    restart: always
    #environment:
    # - GF_SERVER_ROOT_URL=http://my.grafana.server/
    # - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
#     - ./provisioning:/etc/grafana/provisioning
#     - ./dashboards:/var/lib/grafana/dashboards
#     - ./grafana.ini:/etc/grafana/grafana.ini
     - /etc/letsencrypt/live/expmonitor.freeddns.org/privkey.pem:/etc/grafana/grafana.key
     - /etc/letsencrypt/live/expmonitor.freeddns.org/fullchain.pem:/etc/grafana/grafana.crt
     - storage:/var/lib/grafana
    networks:
      - expenses-monitor_default

volumes:
  storage: {}

networks:
  expenses-monitor_default:
    name: expenses-monitor_default
    external: true
