---
# HTTPRoute for Grafana dashboard
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: monitoring
      sectionName: https
  hostnames:
    - grafana.expmonitor.freeddns.org
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}-grafana
          port: 80
