{
 "title": "Andamento generale",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  { "title": "Andamenti totali", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Andamento entrate totali",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select * FROM (select DATE_TRUNC('month',accounting_date) AS time, sum(amount)/100 as entrate, c.name\nFROM payments p\njoin expenses.categories c on p.category_id = c.id\nWHERE $__timeFilter(accounting_date) and amount > 0\nGROUP BY DATE_TRUNC('month', accounting_date), c.name\nUNION\nselect DATE_TRUNC('month',accounting_date) AS time, sum(amount)/100 as entrate, 'totale'\nFROM payments \nWHERE $__timeFilter(accounting_date) and amount > 0\nGROUP BY DATE_TRUNC('month', accounting_date)) unione\norder by time\n\n"
    }
   ]
  },
  {
   "title": "Andamento uscite totali",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, sum(abs(amount)/100) as uscite\nFROM payments \nWHERE $__timeFilter(accounting_date) and amount < 0\nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time\n\n"
    }
   ]
  },
  {
   "title": "Andamento uscite fisse",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select * FROM (select DATE_TRUNC('month',accounting_date) AS time, abs(sum(amount))/100 as uscite_fisse, c.name\nFROM payments p\njoin expenses.categories c on p.category_id = c.id\nWHERE $__timeFilter(accounting_date) and c.name in ('affitto', 'bolletta', 'condominio')\nGROUP BY DATE_TRUNC('month', accounting_date), c.name\nUNION\nselect DATE_TRUNC('month',accounting_date) AS time, sum(amount * -1)/100 as entrate, 'totale'\nFROM payments p\njoin expenses.categories c on p.category_id = c.id\nWHERE $__timeFilter(accounting_date) and c.name in ('affitto', 'bolletta', 'condominio')\nGROUP BY DATE_TRUNC('month', accounting_date)) unione\norder by time\n\n"
    }
   ]
  },
  {
   "title": "Andamento spese mensili per categoria",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 13, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, c.name, abs(sum(amount))/100 as spesa\nfrom expenses.payments p\njoin expenses.categories c on p.category_id = c.id\nwhere $__timeFilter(accounting_date) and amount < 0\nGROUP BY DATE_TRUNC('month', accounting_date), c.name\norder by time"
    }
   ]
  },
  {
   "title": "Raggruppamento spese per categoria",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select accounting_date as time, c.name, abs(amount)/100 as spesa\nfrom expenses.payments p\njoin expenses.categories c on p.category_id = c.id\nwhere $__timeFilter(accounting_date) and amount < 0\norder by time"
    }
   ]
  },
  { "title": "aggregati", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Bilancio mensile",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, sum(amount)/100 as bilancio\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) \nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time"
    }
   ]
  },
  {
   "title": "Ratio utile/entrate",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select time, case when entrate != 0 then (utile::float / entrate::float)*100 else 0 end as ratio_utile_su_entrate\nfrom (select DATE_TRUNC('month',accounting_date) AS time, \n  sum( case when amount > 0 then amount else 0 end) as entrate, \n  sum(amount) as utile\nfrom expenses.payments\nwhere $__timeFilter(accounting_date)\nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time\n) q"
    }
   ]
  },
  {
   "title": "spese_fisse/stipendio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select time, sum(spese) * 100 / sum(entrate) as spese_fisse_stipendio from (\nselect DATE_TRUNC('month', accounting_date) as time, abs(sum(amount)/100)::float as spese, NULL as entrate\nFROM payments p\njoin expenses.categories c on p.category_id = c.id\nwhere c.name in ('affitto', 'bolletta', 'condominio') and $__timeFilter(accounting_date)\ngroup by DATE_TRUNC('month', accounting_date)\nunion\nselect DATE_TRUNC('month', accounting_date) as time, NULL as spese, abs(sum(amount)/100)::float as entrate\nFROM payments p\njoin expenses.categories c on p.category_id = c.id\nwhere c.name in ('stipendio') and $__timeFilter(accounting_date)\ngroup by DATE_TRUNC('month', accounting_date)\n) p\ngroup by time"
    }
   ]
  },
  {
   "title": "affitto/stipendio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select time, sum(spese) * 100 / sum(entrate) as affitto_stipendio_rate from (\nselect DATE_TRUNC('month', accounting_date) as time, abs(sum(amount)/100)::float as spese, NULL as entrate\nFROM payments p\njoin expenses.categories c on p.category_id = c.id\nwhere c.name = 'affitto' and $__timeFilter(accounting_date)\ngroup by DATE_TRUNC('month', accounting_date)\nunion\nselect DATE_TRUNC('month', accounting_date) as time, NULL as spese, abs(sum(amount)/100)::float as entrate\nFROM payments p\njoin expenses.categories c on p.category_id = c.id\nwhere c.name = 'stipendio' and $__timeFilter(accounting_date)\ngroup by DATE_TRUNC('month', accounting_date)\n) p\ngroup by time"
    }
   ]
  },
  {
   "title": "Uscite mensili",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, percentile_disc(0.5) within group (order by abs(payments.amount/100)) as \"p(50)\", avg(abs(amount)/100)\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) and amount < 0\nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time"
    }
   ]
  }
 ]
}