{
 "title": "Monitoraggio mese corrente",
 "time": { "from": "now/M", "to": "now/M" },
 "panels": [
  { "title": "Contatori", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, sum(amount)/100 as bilancio\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) and amount > 0\nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, sum(abs(amount))/100 as bilancio\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) and amount < 0\nGROUP BY DATE_TRUNC('month', accounting_date)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, sum(amount)/100 as bilancio\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) \nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time"
    }
   ]
  },
  {
   "title": "Rapporto tra spese fisse (affitto + bollette + condominio ecc) e stipendio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, sum(spese) * 100 / sum(entrate) as spese_fisse_stipendio from (\nselect DATE_TRUNC('month', accounting_date) as time, abs(sum(amount)/100)::float as spese, NULL as entrate\nFROM payments p\njoin expenses.categories c on p.category_id = c.id\nwhere c.name in ('affitto', 'bolletta', 'condominio') and $__timeFilter(accounting_date)\ngroup by DATE_TRUNC('month', accounting_date)\nunion\nselect DATE_TRUNC('month', accounting_date) as time, NULL as spese, abs(sum(amount)/100)::float as entrate\nFROM payments p\njoin expenses.categories c on p.category_id = c.id\nwhere c.name in ('stipendio') and $__timeFilter(accounting_date)\ngroup by DATE_TRUNC('month', accounting_date)\n) p\ngroup by time"
    }
   ]
  },
  {
   "title": "Dettaglio spese per categoria",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select c.name,\n  abs(sum(amount))/100 as spesa\nFrom\n  payments p\njoin expenses.categories c on p.category_id = c.id\nwhere amount < 0 and $__timeFilter(accounting_date)\ngroup by c.name\norder by spesa desc\n"
    }
   ]
  },
  {
   "title": "Dettaglio entrate",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select c.name,\n  sum(abs(amount))/100 as entrata\nFrom\n  payments p\njoin expenses.categories c on p.category_id = c.id\nwhere amount > 0 and $__timeFilter(accounting_date)\ngroup by c.name\norder by entrata desc"
    }
   ]
  },
  {
   "title": "Variazione spese mesi precedenti (top 10)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select c.name,\r\n  abs(sum(amount))/100 as spesa_previous_month\r\nFrom\r\n  payments p\r\njoin expenses.categories c on p.category_id = c.id\r\nwhere amount < 0 and accounting_date > timestamp ${__from:date:'YYYY-MM-DD'} - interval '1 month' and accounting_date < timestamp ${__to:date:'YYYY-MM-DD'} - interval '1 month' + interval '1 day'\r\ngroup by c.name\r\n"
    },
    {
     "rawSql": "select c.name,\r\n  abs(sum(amount))/100/3 as spesa_media_previous_3_months\r\nFrom\r\n  payments p\r\njoin expenses.categories c on p.category_id = c.id\r\nwhere amount < 0 and accounting_date > timestamp ${__from:date:'YYYY-MM-DD'} - interval '3 month' and accounting_date < timestamp ${__to:date:'YYYY-MM-DD'} - interval '1 month' + interval '1 day'\r\ngroup by c.name\r\n"
    },
    {
     "rawSql": "select c.name,\r\n  abs(sum(amount))/100/12 as spesa_media_last_year\r\nFrom\r\n  payments p\r\njoin expenses.categories c on p.category_id = c.id\r\nwhere amount < 0 and accounting_date > timestamp ${__from:date:'YYYY-MM-DD'} - interval '1 year' and accounting_date < timestamp ${__to:date:'YYYY-MM-DD'} - interval '1 month' + interval '1 day'\r\ngroup by c.name\r\n"
    },
    {
     "rawSql": "select c.name,\n  abs(sum(amount))/100 as spesa_current\nFrom\n  payments p\njoin expenses.categories c on p.category_id = c.id\nwhere amount < 0 and $__timeFilter(accounting_date) \ngroup by c.name\norder by spesa_current desc\nlimit 10\n"
    }
   ]
  },
  {
   "title": "Uscite cumulate per giorno",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('day',accounting_date) AS time,\n  sum(abs(amount))/100 as spesa\nFrom\n  payments\nwhere amount < 0 and $__timeFilter(accounting_date)\ngroup by time\norder by time\n"
    }
   ]
  },
  { "title": "Andamenti", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Estratto conto",
   "type": "table",
   "gridPos": { "h": 90, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "select p.id, accounting_date, merchant_name, amount /100.0 as amount, c.name, w.name as wallet, description\r\nfrom payments p\r\njoin wallets w on p.wallet_id = w.id\r\njoin expenses.categories c on p.category_id = c.id\r\nWHERE $__timeFilter(accounting_date) \r\nORDER BY accounting_date asc\r\n"
    }
   ]
  }
 ]
}