{
 "title": "Mezzi di trasporto",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mezzo",
    "label": "mezzi trasporto",
    "query": "select value from expenses.payments_tags pt where pt.key = 'mezzo'"
   }
  ]
 },
 "panels": [
  { "title": "$mezzo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "mezzo" },
  {
   "title": "Recap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select max(pt.value)::numeric - min(pt.value)::numeric as \"km percorsi\"\nfrom payments_tags pt\njoin payments p on p.id = pt.payment_id\nwhere pt.payment_id in (select p.id from payments p join payments_tags pt on p.id = pt.payment_id where pt.key = 'mezzo' and pt.value = $mezzo)\nand pt.key = 'km'"
    },
    {
     "rawSql": "select sum(litri) as \"litri carburante\" from (\n  select (abs(p.amount)/100) /  (pt.value::numeric/1000) as litri\n  from payments_tags pt\n  join payments p on p.id = pt.payment_id\n  where pt.payment_id in (select p.id from payments p join payments_tags pt on p.id = pt.payment_id where pt.key = 'mezzo' and pt.value = $mezzo)\n  and pt.key = 'costo'\n)"
    },
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Spesa totale",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select amount::float/100 from expenses.payments_tags pt \njoin expenses.payments p on p.id = pt.payment_id \nwhere pt.value = $mezzo;"
    }
   ]
  },
  {
   "title": "Spesa ultimo anno",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select amount::float/100 from expenses.payments_tags pt \njoin expenses.payments p on p.id = pt.payment_id \nwhere pt.value = $mezzo and p.accounting_date > now() - interval '1 year';"
    }
   ]
  },
  {
   "title": "Spesa ultimi 6 mesi",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select amount::float/100 from expenses.payments_tags pt \njoin expenses.payments p on p.id = pt.payment_id \nwhere pt.value = $mezzo and p.accounting_date > now() - interval '6 months';"
    }
   ]
  },
  {
   "title": "Suddivisione spese per esercente",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select accounting_date as time, merchant_name, sum(abs(amount))::float/100 as spesa\nfrom expenses.payments p\njoin expenses.payments_tags pt on p.id = pt.payment_id \nwhere pt.value = $mezzo and p.amount < 0\ngroup by accounting_date, merchant_name\norder by time"
    }
   ]
  },
  {
   "title": "Suddivisione spese per categoria",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select accounting_date as time, c.name, sum(abs(amount))::float/100 as spesa\nfrom expenses.payments p\njoin expenses.payments_tags pt on p.id = pt.payment_id \njoin expenses.categories c on p.category_id = c.id\nwhere pt.value = $mezzo and p.amount < 0\ngroup by accounting_date, c.name\norder by time"
    }
   ]
  },
  {
   "title": "Elenco spese",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select p.accounting_date, p.merchant_name,  c.name, abs(amount)::float/100 as spesa, p.description\nfrom expenses.payments_tags pt\njoin expenses.payments p on p.id = pt.payment_id\njoin expenses.categories c on p.category_id = c.id\nwhere pt.key = 'mezzo' and pt.value = $mezzo and p.amount < 0\norder by accounting_date desc\n"
    }
   ]
  }
 ]
}