{
 "title": "Ticket & welfare",
 "time": { "from": "2022-09-30T22:00:00.000Z", "to": "now" },
 "panels": [
  { "title": "ticket restaurant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "bilancio complessivo",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select wallet_id, sum(amount)/100 from payments p\nWHERE wallet_id = (select id from wallets w where name = 'ticket')\ngroup by wallet_id"
    }
   ]
  },
  {
   "title": "bilancio mensile ticket",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) AS time, sum(amount)/100 as bilancio\nfrom expenses.payments\nwhere $__timeFilter(accounting_date) and wallet_id = (select id from wallets where name = 'ticket')\nGROUP BY DATE_TRUNC('month', accounting_date)\norder by time"
    }
   ]
  },
  {
   "title": "spese ticket per merchant",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select merchant_name, sum(amount)/-100 as co\nfrom payments \nwhere $__timeFilter(accounting_date) and wallet_id = (select id from wallets where name = 'ticket') and amount < 0\ngroup by merchant_name"
    }
   ]
  },
  {
   "title": "split entrate/uscite ticket",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month',accounting_date) as time, 'entrate', sum(amount)/100 as ticket\nfrom payments \nwhere wallet_id = (select id from wallets where name = 'ticket') and $__timeFilter(accounting_date) and amount > 0\ngroup by wallet_id, DATE_TRUNC('month',accounting_date)\nUNION\nselect DATE_TRUNC('month',accounting_date) as time, 'uscite', sum(amount)/100 as entrate\nfrom payments \nwhere wallet_id = (select id from wallets where name = 'ticket') and $__timeFilter(accounting_date) and amount < 0\ngroup by wallet_id, DATE_TRUNC('month',accounting_date)\norder by time"
    }
   ]
  },
  {
   "title": "welfare 2022",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "entrata complessiva",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select wallet_id, sum(amount)/100 from payments\nWHERE wallet_id = (select id from wallets where name = 'welfare22') and amount > 0\ngroup by wallet_id"
      }
     ]
    },
    {
     "title": "saldo Tezenis",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select wallet_id, sum(amount)/100 from payments\nWHERE wallet_id = (select id from wallets where name = 'welfare22') and merchant_name = 'Tezenis'\ngroup by wallet_id"
      }
     ]
    },
    {
     "title": "saldo H&M",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 10, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select wallet_id, sum(amount)/100 from payments\nWHERE wallet_id = (select id from wallets where name = 'welfare22') and merchant_name = 'H&M'\ngroup by wallet_id"
      }
     ]
    },
    {
     "title": "saldo buoni edenred",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select wallet_id, sum(amount)/100 from payments\nWHERE wallet_id = (select id from wallets where name = 'welfare22') and merchant_name not in('Tezenis', 'H&M')\ngroup by wallet_id"
      }
     ]
    },
    {
     "title": "saldo totale",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "select sum(amount)/100 as bilancio\nfrom expenses.payments\nwhere wallet_id = (select id from wallets where name = 'welfare22')"
      }
     ]
    },
    {
     "title": "spese welfare per merchant",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "select merchant_name, sum(amount)/-100 as co\nfrom payments \nwhere $__timeFilter(accounting_date) and wallet_id = (select id from wallets where name = 'welfare22') and amount < 0\ngroup by merchant_name\n"
      }
     ]
    }
   ]
  },
  {
   "title": "welfare 2023",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "entrata complessiva",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "select wallet_id, sum(amount)/100.0 as amount\nfrom payments\nWHERE wallet_id = (select id from wallets where name = 'welfare23') and amount > 0\ngroup by wallet_id"
      }
     ]
    },
    {
     "title": "saldo buoni edenred",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select wallet_id, sum(amount)/100 from payments\nWHERE wallet_id = (select id from wallets where name = 'welfare23') and merchant_name not in('Tezenis', 'H&M')\ngroup by wallet_id"
      }
     ]
    },
    {
     "title": "saldo totale",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 10, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "select sum(amount)/100.0 as bilancio\nfrom expenses.payments\nwhere wallet_id = (select id from wallets where name = 'welfare23')"
      }
     ]
    },
    {
     "title": "buono carburante",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 7, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "select wallet_id, sum(amount)/100.0 as amount\nfrom payments\nWHERE wallet_id = (select id from wallets where name = 'bonus-carburante23')\ngroup by wallet_id"
      }
     ]
    },
    {
     "title": "spese welfare per merchant",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "select merchant_name, sum(amount)/-100 as co\nfrom payments \nwhere wallet_id = (select id from wallets where name = 'welfare23') and amount < 0\ngroup by merchant_name\n"
      }
     ]
    }
   ]
  },
  { "title": "welfare 2024", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "entrata complessiva",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select wallet_id, sum(amount)/100.0 as amount\nfrom payments\nWHERE wallet_id = (select id from wallets where name = 'welfare24') and amount > 0\ngroup by wallet_id"
    }
   ]
  },
  {
   "title": "saldo totale",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select sum(amount)/100.0 as bilancio\nfrom expenses.payments\nwhere wallet_id = (select id from wallets where name = 'welfare24')"
    }
   ]
  },
  {
   "title": "spese welfare per merchant",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select merchant_name, sum(amount)/-100 as co\nfrom payments \nwhere wallet_id = (select id from wallets where name = 'welfare24') and amount < 0\ngroup by merchant_name\n"
    }
   ]
  },
  { "title": "welfare 2025", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "entrata complessiva",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select wallet_id, sum(amount)/100.0 as amount\nfrom payments\nWHERE wallet_id = (select id from wallets where name = 'welfare25') and amount > 0\ngroup by wallet_id"
    }
   ]
  },
  {
   "title": "saldo totale",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select sum(amount)/100.0 as bilancio\nfrom expenses.payments\nwhere wallet_id = (select id from wallets where name = 'welfare25')"
    }
   ]
  },
  {
   "title": "spese welfare per merchant",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select merchant_name, sum(amount)/-100 as co\nfrom payments \nwhere wallet_id = (select id from wallets where name = 'welfare25') and amount < 0\ngroup by merchant_name\n"
    }
   ]
  }
 ]
}