{
 "title": "Viaggi",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "viaggi",
    "query": "select value from expenses.payments_tags pt where pt.key = 'viaggio'"
   }
  ]
 },
 "panels": [
  { "title": "$viaggi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "viaggi" },
  {
   "title": "Spesa totale",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select amount::float/100 from expenses.payments_tags pt \njoin expenses.payments p on p.id = pt.payment_id \nwhere pt.value = $viaggi;"
    }
   ]
  },
  {
   "title": "Suddivisione spese per merchant",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select accounting_date as time, merchant_name, sum(abs(amount))::float/100 as spesa\nfrom expenses.payments p\njoin expenses.payments_tags pt on p.id = pt.payment_id \nwhere pt.value = $viaggi and p.amount < 0\ngroup by accounting_date, merchant_name\norder by time"
    }
   ]
  },
  {
   "title": "Suddivisione spese per categoria",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select accounting_date as time, c.name, sum(abs(amount))::float/100 as spesa\nfrom expenses.payments p\njoin expenses.payments_tags pt on p.id = pt.payment_id \njoin expenses.categories c on p.category_id = c.id\nwhere pt.value = $viaggi and p.amount < 0\ngroup by accounting_date, c.name\norder by time"
    }
   ]
  }
 ]
}