version: "3.9"
services:
  postgres:
    image: postgres:15.3-alpine3.18
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        failure_action: rollback
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - expenses_monitor
    secrets:
      - POSTGRES_PASSWORD

volumes:
  database: {}

networks:
  expenses_monitor:
    external: true

secrets:
  POSTGRES_PASSWORD:
    external: true