auth:
  existingSecret: postgresql
  secretKeys:
    adminPasswordKey: "postgres-password"
  database: expenses-monitor
  usePasswordFiles: true

primary:
  initdb:
    scriptsConfigMap: postgresql-init-schema
    scriptsSecret: postgresql-init-user-script
