postgresql:
  auth:
    existingSecret: postgresql
    secretKeys:
      adminPasswordKey: "postgres-password"
    database: expenses-monitor
    usePasswordFiles: true

  primary:
    initdb:
      scriptsConfigMap: postgresql-init-schema
      scriptsSecret: postgresql-init-user-script
    # PostgreSQL configuration to enable pg_stat_statements for query metrics
    extendedConfiguration: |
      shared_preload_libraries = 'pg_stat_statements'
      pg_stat_statements.track = all

  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/postgres-exporter
      tag: "0.15.0-debian-12-r39"
    serviceMonitor:
      enabled: true
      interval: 30s
      additionalLabels: {}
    collectors:
      stat_statements: true
