spring:
  config:
    import: "optional:configtree:/run/secrets/"

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}

feign:
  url: ${BACKEND_URL:http://localhost:8443}

