spring:
  r2dbc:
    url: ${DB_CONNECTION_URI:r2dbc:postgresql://localhost:5432/postgres}
    schema: ${DB_SCHEMA:expenses}
    username: ${DB_BACKEND_USER:postgres}
    password: ${DB_BACKEND_PASSWORD:postgres}
    pool.validation-query: SELECT 1

basic-auth:
  username: ${BASIC_AUTH_USERNAME:user}
  password: ${BASIC_AUTH_PASSWORD:{bcrypt}$2a$10$lnno9KSTgXgzXPidwsN0nudlqzMhd4Ls/9W122onLGQEgWUeydUmm} # "pwd" as default

frontend:
  origin: ${FRONTEND_ORIGIN_URL:http://localhost:5173}

logging.level._reactor.netty.channel.LeakDetection: debug
