---
# NetworkPolicy for PostgreSQL
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgresql-netpol
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/component: primary
  policyTypes:
    - Ingress
  
  ingress:
    # Allow only from backend-rust and migration job
    - from:
      - namespaceSelector:
          matchLabels:
            name: expenses-monitor
        podSelector:
          matchLabels:
            app: keycloak
      - namespaceSelector:
          matchLabels:
            name: expenses-monitor
        podSelector:
          matchLabels:
            app: keycloak
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: expenses-monitor
        podSelector:
          matchLabels:
            app: backend-rust
      - namespaceSelector:
          matchLabels:
            name: expenses-monitor
        podSelector:
          matchLabels:
            job-name: backend-rust-db-migration
      ports:
        - protocol: TCP
          port: 5432
