apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    postgres-password: AgAA7zPNUR0tybc/wOfFHa4dxFTsYcEh5sqIgAsGUTBOO4hcvIhF6ZJWbiC2VUlb8R6KKUEvmz5FGlsKCUv2WErRKLMCHnJ7no2ButJAT5JoTB6TE0n2Q8Y5n0ZVZkSiv0tKfaW3SUWmEVqs0J+eKIVYNW3bJx+00K1C0X+SswoE23Knojco7gABjzhF0VYdPfajb9mexiu9Kk1Md3z7ZQCE3ZBkMi3/MRN++LQ1+P6An5TP3lb5LKWcdJoirUlq6MF82SYQAI1Ro7FBcTisO+DuEJ/CafNOFSAgd57VKovNNYEoHzSfWb1KfhHIOpjhIzq/86SrFXVTo2Xa8qHny2OEdBeLhB7BMTWq5DGSlCuSk2FLpiEZGtQswa58QVtz7PWE/qE9d1qEMKlU7FzUBGM3jMlqRVBCwzqjwr0jPRNQMqC/k2gdNJIdEnSp6Ao5x+5+gao9mKuTLRVsD0wtqgAfw42ZITe9omtKQiaYDH3JFeuuR8M9BP9Q1EnbWuvGHYc0EniMYuiXdzuy3R1lOcT1NyIMlDUtJnrKoZ7MwSfouPEXVoMEPXyOD+CgqMr7FsI+Ud8xXhiRBWQHzEqPmKds28RIfYmzbplBEgnZ+g0tXpxYwvpuGwk8gQtRVgHJzOMlpj9qS9z3+rLkeVUBsqU7DJ113ynullejVga34V6oX/5iBAF2LBrk9DBfIkfEeRqUKo/muqXku+ocWNmAlXVLaQ1JkA1Kd00=
  template:
    metadata:
      name: postgresql
      namespace: default
    type: Opaque

---
#
#apiVersion: bitnami.com/v1alpha1
#kind: SealedSecret
#metadata:
#  name: users-secret
#spec:
#  encryptedData:
#    KEYCLOAK_DB:
#    KEYCLOAK_PASSWORD:
#    KEYCLOAK_USER:
