grafana:
  plugins:
    - https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/releases/download/v1.3.0/mahendrapaipuri-dashboardreporter-app-1.3.0.zip;mahendrapaipuri-dashboardreporter-app

  grafana.ini:
    plugins:
      allow_loading_unsigned_plugins: mahendrapaipuri-dashboardreporter-appapp
