### Workflow to run the api test against the backend

name: Run API test

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      API_TEST_CLIENT_ID:
        required: true
      API_TEST_CLIENT_SECRET:
        required: true

jobs:
  ApiTest:
    name: API Test
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 #4.0.0
        with:
          node-version: 20

      - name: Install newman
        run: npm install -g newman

      - name: Run postman collection
        run: newman run postman/expenses-monitor_api_test.postman_collection.json -e postman/expenses-monitor.postman_environment.json --env-var "CLIENT_ID=${{ secrets.API_TEST_CLIENT_ID }}" --env-var "CLIENT_SECRET=${{ secrets.API_TEST_CLIENT_SECRET }}"
