name: 'Build Grafana Image'

on:
  workflow_dispatch:

jobs:
  BuildGrafanaImage:
    name: 'Build Grafana'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 #v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 #v3.0.0

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d #v3.0.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image
        if: steps.changed-path.outputs.dockerfile == 'true'
        id: docker_build_push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 #v6.7.0
        with:
          context: monitoring/grafana
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:grafana-11.1.4-chromium
          platforms: linux/amd64,linux/arm64
