### Action to build and push image on GHCR

name: Build and push image for aarch64 - backend-rust

on:
  workflow_dispatch:
    inputs:
      enabled:
        required: false
        type: string
        description: 'Flag to enable the build and push'
        default: 'true'
      version:
        description: 'Tag'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      enabled:
        required: true
        type: string
        default: false
    secrets:
      VM_HOST:
        required: true
      VM_USERNAME:
        required: true
      VM_PRIVATE_KEY:
        required: true
      VM_PORT:
        required: true

jobs:

  BuildAndPush:
    name: BuildAndPush
    runs-on: ubuntu-latest
    environment: prod
    if: inputs.enabled == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 #v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 #v3.0.0

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d #v3.0.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image
        id: docker_build_push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 #v5.0.0
        with:
          context: backend-rust
          file: backend-rust/Dockerfile_aarch64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:backend-rust-latest-aarch64
            ghcr.io/${{ github.repository }}:${{ github.sha }}-aarch64
            ghcr.io/${{ github.repository }}:${{ inputs.version }}-aarch64
