### Action to build and run the unit tests of backend

name: Build backend

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  Build:
    name: GradleBuild
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: 0

      - name: Execute Gradle build
        run: |
          cd backend
          ./gradlew build
