### Action to Deploy Grafana on VM

name: GrafanaDeploy

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      VM_HOST:
        required: true
      VM_USERNAME:
        required: true
      VM_PRIVATE_KEY:
        required: true
      VM_PORT:
        required: true

jobs:

  GrafanaDeploy:
    name: Build and Deploy Grafana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc #v2.2.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and Push image to ghcr'
        run: |
          cd grafana
          docker buildx create --name mybuilder --bootstrap --use
          docker buildx ls
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/and-mora/expenses-monitor:grafana-latest -t ghcr.io/and-mora/expenses-monitor:${{ inputs.version }} .
          docker push --all-tags ghcr.io/and-mora/expenses-monitor

      - name: 'Deploy grafana on docker in VM'
        uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            mkdir -p expenses-monitor/grafana
            cd expenses-monitor/grafana
            wget -O docker-compose.yml https://raw.githubusercontent.com/and-mora/expenses-monitor/${{ inputs.version }}/grafana/docker-compose.yml
            echo VERSION=${{ inputs.version }} > .env
            sudo docker compose up -d
