### Action to Deploy Grafana on VM

name: DeployGrafana

on:
  pull_request:
    branches: [ master ]
#    paths:
#      include:
#        - grafana/*

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy grafana on docker in VM
        uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: ls -al
