### Action to Deploy Grafana on VM

name: DeployGrafana

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#    paths:
#      include:
#        - grafana/*
#  workflow_run:
#    workflows: [SemVer]
#    types:
#      - completed

jobs:

  deploy:
    name: Deploy on VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3

      - name: build and push image to ghcr
        run: |
          cd grafana
#          docker build -t ghcr.io/and-mora/expenses-monitor:grafana_latest -t ghcr.io/and-mora/expenses-monitor:<VERSION> .

      - name: deploy grafana on docker in VM
        uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            docker compose build web
            docker compose up --no-deps -d web
