name: Deploy Alloy

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      VM_HOST:
        required: true
      VM_USERNAME:
        required: true
      VM_PRIVATE_KEY:
        required: true
      VM_PORT:
        required: true

jobs:
  k8sDeploy:
    name: k8sDeploy
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: 'Deploy on k8s'
        uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262 #v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          fingerprint: ${{ secrets.HOST_FINGERPRINT }}
          script: |
            mkdir -p expenses-monitor/monitoring/alloy && cd expenses-monitor/monitoring/alloy
            wget -O Chart.yaml https://raw.githubusercontent.com/and-mora/expenses-monitor/master/monitoring/alloy/Chart.yaml
            wget -O config.alloy https://raw.githubusercontent.com/and-mora/expenses-monitor/master/monitoring/alloy/config.alloy
            kubectl create cm alloy-config --from-file=config.alloy --dry-run=client -o yaml -n monitoring | kubectl apply -f -
            helm dependency build
            helm upgrade --install alloy charts/* -f values.yaml --wait --timeout 300s -n monitoring
