### Workflow that generates a report

name: Generate grafana report

on:
  workflow_dispatch:

jobs:
  Report:
    name: Generate a report
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Retrieve service account ID
        run: |
          echo "SA_ID=$(curl --location 'https://${{ secrets.VM_HOST }}:3000/api/serviceaccounts/search?query=grafana-reporter' \
            --header 'Authorization: Basic ${{ secrets.GF_VIEWER_BASIC_AUTH }}' \
          | jq '.serviceAccounts[0].id')" >> $GITHUB_ENV

      - name: Create service account token with ttl 3m
        run: |
          echo "SA_TOKEN=$(curl -X POST --location 'https://${{ secrets.VM_HOST }}:3000/api/serviceaccounts/${{ env.SA_ID }}/tokens' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Basic ${{ secrets.GF_VIEWER_BASIC_AUTH }}' \
            --data "{
              \"name\": \"report-$(date +%s)\",
              \"secondsToLive\": 180
            }" | jq -r '.key' )" >> $GITHUB_ENV

      - name: Download the report
        run: |
          curl --location 'https://${{ secrets.VM_HOST }}:3000/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=d0a30598-95a5-4098-89cc-435d965df315&from=now-1M%2FM&to=now-1M%2FM&layout=grid' \
            --header "Authorization: Bearer ::add-mask::${{ env.SA_TOKEN }}" \
            --output report.pdf

      - run: ls -al
