name: Tag and Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      enabled:
        required: true
        type: string
        default: false

jobs:
  tag-and-release:
    name: Tag and Release
    runs-on: ubuntu-latest

    steps:
      - name: Create Tag and Publish Release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 #v1.13.0
        if: inputs.enabled == 'true'
        with:
          tag: ${{ inputs.tag }}
          commit: ${{ github.sha }}
          skipIfReleaseExists: true
          generateReleaseNotes: true
