### Publish a GitHub Release with the input tag. If the tag does not exist create it.

name: Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      enabled:
        required: true
        type: string
        default: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: inputs.enabled == 'true'

    steps:
      - name: Create Tag and Publish Release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 #v1.14.0
        with:
          tag: ${{ inputs.tag }}
          commit: ${{ github.sha }}
          skipIfReleaseExists: true
          generateReleaseNotes: true
