
name: Trivy scan

on:
  push:
    branches:
      - master
      - develop
    paths:
      - backend
  pull_request:
    branches:
      - master
      - develop
    paths:
      - backend

jobs:
  Trivy-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name: Build an image from Dockerfile
        run: |
          cd backend
          docker build -t docker.io/andmora/expenses-monitor:backend-${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@d6df5fbcda878e43e5e02484304726ebe7c6c418 #0.47.0
        with:
          image-ref: 'docker.io/andmora/expenses-monitor:backend-${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@df32e399139a3050671466d7d9b3cbacc1cfd034 #2.15.2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
