### Action to build and run the unit tests of backend

name: Update backend version

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  Build:
    name: Update Gradle version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_PAT }}

      - name: "Update of gradle.properties with the new version"
        run: |
          sed -i -e "s/version=.*/version=${{ inputs.version }}/g" backend/gradle.properties

      - name: "Push of gradle.properties with the new version"

        run: |
          git config user.name "GitHub Workflow"
          git config user.email "<>"
          git add backend/gradle.properties
          git commit -m "Updated with new version ${{ inputs.version }}"
          git push origin master
